language: ruby

git:
  submodules: false

env:
  global:
  - AWS_DEFAULT_REGION=us-east-2 
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - echo "Installing Test Gems"
  - gem install yaml-lint

install: true

script:
  - aws cloudformation validate-template --template-body file://cloudtrail-cf-template.yml
  - yaml-lint cloudtrail-cf-template.yml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation Template Validated"
  - echo "YAML Linted"
